// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOxwBOABK5ee23LpbF_RR-UbzLds7jyQ',
    appId: '1:1001400212275:web:6868b17b796f217903fc46',
    messagingSenderId: '1001400212275',
    projectId: 'smartdoc-bf7a3',
    authDomain: 'smartdoc-bf7a3.firebaseapp.com',
    storageBucket: 'smartdoc-bf7a3.firebasestorage.app',
    measurementId: 'G-5B3589JVHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrGInPSAJpmVvy3TIwV6CI5FFn7QEgMo',
    appId: '1:1001400212275:android:d904598eab028a4d03fc46',
    messagingSenderId: '1001400212275',
    projectId: 'smartdoc-bf7a3',
    storageBucket: 'smartdoc-bf7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDLRjqofEAr3wuo1v_uR76rzMOCQwuAw',
    appId: '1:1001400212275:ios:1e60ae1744bf3fee03fc46',
    messagingSenderId: '1001400212275',
    projectId: 'smartdoc-bf7a3',
    storageBucket: 'smartdoc-bf7a3.firebasestorage.app',
    iosBundleId: 'com.example.smartdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDLRjqofEAr3wuo1v_uR76rzMOCQwuAw',
    appId: '1:1001400212275:ios:1e60ae1744bf3fee03fc46',
    messagingSenderId: '1001400212275',
    projectId: 'smartdoc-bf7a3',
    storageBucket: 'smartdoc-bf7a3.firebasestorage.app',
    iosBundleId: 'com.example.smartdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgOxwBOABK5ee23LpbF_RR-UbzLds7jyQ',
    appId: '1:1001400212275:web:772784d240fa9b7503fc46',
    messagingSenderId: '1001400212275',
    projectId: 'smartdoc-bf7a3',
    authDomain: 'smartdoc-bf7a3.firebaseapp.com',
    storageBucket: 'smartdoc-bf7a3.firebasestorage.app',
    measurementId: 'G-HJ6WNBSHGS',
  );
}
